#!/usr/bin/env python3
"""Copy the SKILL.md frontmatter into every file that repeats it.

SKILL.md is the source. This script writes:
  .claude-plugin/marketplace.json    one Claude Code plugin per skill, with its description
  .codex-plugin/plugin.json          the Codex plugin (all skills)
  .cursor-plugin/plugin.json         the Cursor plugin (all skills)
  .cursor-plugin/marketplace.json    the Cursor marketplace entry
  .agents/plugins/marketplace.json   the Codex repo marketplace
  plugin.json                        the portable plugin manifest (agent-plugins.org)
  README.md                          the skill table and the skill count badge
  AGENTS.md                          the skill table

Run from the repo root: python3 scripts/sync-descriptions.py [--check]
--check changes nothing and exits 1 when a file is out of date.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import skillmeta  # noqa: E402

REPO = "https://github.com/EVtivity/evtivity-skills"
HOMEPAGE = "https://www.evtivity.com/docs"
SUMMARY = (
    "Agent Skills for the EVtivity CSMS (OCPP 1.6 and 2.1): set up, configure, deploy, "
    "operate, test, integrate, troubleshoot and report issues."
)
AUTHOR = {"name": "EVtivity", "url": "https://www.evtivity.com"}
KEYWORDS = ["evtivity", "csms", "ocpp", "ev-charging", "charging-stations", "agent-skills"]
START = "<!-- skills:start (generated by scripts/sync-descriptions.py) -->"
END = "<!-- skills:end -->"


def as_json(data: object) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def cell(text: str) -> str:
    return text.replace("|", "/")


def section(skill: skillmeta.Skill) -> str:
    return skill.metadata.get("evtivity-docs-section", "") or "task"


def replace_block(text: str, block: str, path: str) -> str:
    if START not in text or END not in text:
        raise SystemExit(f"{path}: markers {START} and {END} missing")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n{block}{END}{tail}"


def render(skills: list[skillmeta.Skill]) -> dict[str, str]:
    version = skills[0].metadata.get("evtivity-version", "0.0.0")
    out: dict[str, str] = {}
    out[".claude-plugin/marketplace.json"] = as_json(
        {
            "name": "evtivity-skills",
            "owner": {"name": "EVtivity"},
            "metadata": {"description": SUMMARY},
            "plugins": [
                {
                    "name": s.name,
                    "description": s.description,
                    "source": "./",
                    "strict": False,
                    "skills": [f"./skills/{s.name}"],
                }
                for s in skills
            ],
        }
    )
    out[".codex-plugin/plugin.json"] = as_json(
        {
            "name": "evtivity",
            "version": version,
            "description": SUMMARY,
            "author": AUTHOR,
            "homepage": HOMEPAGE,
            "repository": REPO,
            "license": "MIT",
            "keywords": KEYWORDS,
            "skills": "./skills/",
            "interface": {
                "displayName": "EVtivity",
                "shortDescription": "EVtivity CSMS skills",
                "longDescription": SUMMARY,
                "developerName": "EVtivity",
                "category": "Developer Tools",
                "capabilities": ["Interactive", "Write"],
                "websiteURL": HOMEPAGE,
                "defaultPrompt": [
                    "Stand up EVtivity locally with Docker",
                    "Why can't my charging station connect to EVtivity?",
                    "List the active charging sessions through the EVtivity API",
                ],
                "composerIcon": "./assets/evtivity-logo.svg",
                "logo": "./assets/evtivity-logo.svg",
            },
        }
    )
    out[".cursor-plugin/plugin.json"] = as_json(
        {
            "name": "evtivity",
            "version": version,
            "description": SUMMARY,
            "author": AUTHOR,
            "keywords": KEYWORDS,
            "logo": "assets/evtivity-logo.svg",
        }
    )
    out[".cursor-plugin/marketplace.json"] = as_json(
        {
            "name": "evtivity",
            "owner": {"name": "EVtivity"},
            "plugins": [{"name": "evtivity", "source": "./", "description": SUMMARY}],
        }
    )
    out[".agents/plugins/marketplace.json"] = as_json(
        {
            "name": "evtivity",
            "interface": {"displayName": "EVtivity"},
            "plugins": [
                {
                    "name": "evtivity",
                    "source": {"source": "local", "path": "./"},
                    "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
                    "category": "Developer Tools",
                }
            ],
        }
    )
    out["plugin.json"] = as_json(
        {
            "$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json",
            "name": "evtivity",
            "version": version,
            "description": SUMMARY,
            "author": AUTHOR,
            "homepage": HOMEPAGE,
            "repository": REPO,
            "license": "MIT",
            "keywords": KEYWORDS,
        }
    )

    readme = Path("README.md").read_text(encoding="utf-8")
    rows = ["| Skill | Description |", "|---|---|"]
    rows += [f"| `{s.name}` | {cell(s.description)} |" for s in skills]
    readme = replace_block(readme, "\n".join(rows) + "\n", "README.md")
    readme = re.sub(r"badge/Skills-\d+-", f"badge/Skills-{len(skills)}-", readme)
    readme = re.sub(r'alt="Skills: \d+"', f'alt="Skills: {len(skills)}"', readme)
    out["README.md"] = readme

    agents = Path("AGENTS.md").read_text(encoding="utf-8")
    rows = ["| Skill | Path | Docs section | Description |", "|---|---|---|---|"]
    rows += [
        f"| {s.name} | `skills/{s.name}/SKILL.md` | {section(s)} | {cell(s.description)} |"
        for s in skills
    ]
    out["AGENTS.md"] = replace_block(agents, "\n".join(rows) + "\n", "AGENTS.md")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, content in render(skillmeta.load()).items():
        path = Path(name)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(name)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if args.check and stale:
        for name in stale:
            print(f"ERROR {name} is out of date. Run python3 scripts/sync-descriptions.py")
        return 1
    print(f"{'stale' if args.check else 'updated'}: {', '.join(stale) or 'none'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
